use_frameworks!

target 'NativescriptPlayground_Example' do
  pod 'NativescriptPlayground', :path => '../'

  target 'NativescriptPlayground_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
